#!/usr/bin/env python3
"""Add 12 Contra Costa County vendors to all-vendors.csv."""

import csv
from datetime import datetime, timezone

CSV_PATH = "data/enriched/all-vendors.csv"
TIMESTAMP = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")

HEADERS = [
    "county", "vendor_name", "instructor_names", "email", "phone",
    "website_url", "booking_capability", "city", "state", "address",
    "price_16hr_full", "price_8hr_renewal", "price_add_a_gun",
    "vendor_description", "crawl_status", "enrichment_confidence",
    "confidence_notes", "logo_path", "instructor_image_paths",
    "training_image_paths", "enriched_at",
]

vendors = [
    # --- 8 existing vendors re-listed for contra-costa ---
    {
        "county": "contra-costa",
        "vendor_name": "Defensive Accuracy, LLC",
        "instructor_names": "Denise King",
        "email": "",
        "phone": "(209) 369-9366",
        "website_url": "https://www.daccw.com/ccw-classes",
        "booking_capability": "inquiry_only",
        "city": "",
        "state": "CA",
        "address": "",
        "price_16hr_full": "",
        "price_8hr_renewal": "",
        "price_add_a_gun": "",
        "vendor_description": "Defensive Accuracy, LLC has been training law-abiding Californians in concealed carry since 2006. All instructors are certified by the California Department of Justice as CCW instructors. They offer 16-hour initial CCW classes and 8-hour renewal classes in Concord and Richmond, as well as private and semi-private instruction options.",
        "crawl_status": "success",
        "enrichment_confidence": "low",
        "confidence_notes": "Re-listed from marin county entry. Found vendor description and service offerings but no pricing information, specific addresses, or clear booking process details.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Friedman Firearms Training",
        "instructor_names": "",
        "email": "",
        "phone": "(925) 818-6642",
        "website_url": "https://www.friedmanfirearmstraining.com",
        "booking_capability": "inquiry_only",
        "city": "Pleasant Hill",
        "state": "CA",
        "address": "",
        "price_16hr_full": "",
        "price_8hr_renewal": "",
        "price_add_a_gun": "",
        "vendor_description": "Friedman Firearms Training provides CCW training by appointment in compliance with PC26165 SB2 requirements for both initial and renewal applications. They specialize in one-on-one training sessions rather than group classes for personalized instruction. The company also offers mobile CCW training services and comprehensive online animated lessons on shooting fundamentals including aiming, grip control, trigger control, and breath control.",
        "crawl_status": "success",
        "enrichment_confidence": "low",
        "confidence_notes": "Re-listed from santa-clara county entry. No pricing information found. Must call/email for appointments. No street address available.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Paladin Tactical US",
        "instructor_names": "Dan Butler",
        "email": "paladintacticalus@gmail.com",
        "phone": "(707) 863-1064",
        "website_url": "https://www.paladin-tactical-us.com",
        "booking_capability": "unclear",
        "city": "Concord",
        "state": "CA",
        "address": "4700 Evora Rd, Concord, CA 94520",
        "price_16hr_full": "",
        "price_8hr_renewal": "",
        "price_add_a_gun": "",
        "vendor_description": "Paladin Tactical is a Bay Area firearms training provider that offers CCW classes along with advanced pistol, rifle, shotgun, and scenario-based training. They serve responsible citizens, law enforcement, and security professionals, conducting training at the United Sportsmen range in Concord, CA. The company emphasizes professional and safe training environments with experienced instructors.",
        "crawl_status": "success",
        "enrichment_confidence": "low",
        "confidence_notes": "Re-listed from marin county entry. No pricing information or specific booking process details found.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "2nd Amendment Firearms Academy",
        "instructor_names": "Doug Kevilus",
        "email": "contact@2aFirearmsAcademy.com",
        "phone": "(707) 410-0389",
        "website_url": "https://www.2afirearmsacademy.com",
        "booking_capability": "unclear",
        "city": "Fairfield",
        "state": "CA",
        "address": "",
        "price_16hr_full": "400",
        "price_8hr_renewal": "250",
        "price_add_a_gun": "",
        "vendor_description": "2A Firearms Academy is a Bay Area-based firearms training company founded by U.S. Army veteran Doug Kevilus and co-founder Ryan Lewis. The academy specializes in California CCW certification and defensive firearms training, serving over 30 jurisdictions across the Bay Area. Their instructors are DOJ certified CCW instructors with backgrounds in military and competitive shooting, offering comprehensive training that combines classroom instruction with live-fire exercises at outdoor ranges.",
        "crawl_status": "success",
        "enrichment_confidence": "medium",
        "confidence_notes": "Re-listed from sonoma county entry. Clear pricing for 16hr CCW ($400) and 8hr renewal ($250). No specific address or clear booking process.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Expert Firearms Training LLC",
        "instructor_names": "Roy Bryson",
        "email": "Roy@expertfirearmstraining.com",
        "phone": "(925) 550-2780",
        "website_url": "https://www.goxswat.com",
        "booking_capability": "",
        "city": "Tracy",
        "state": "CA",
        "address": "",
        "price_16hr_full": "",
        "price_8hr_renewal": "",
        "price_add_a_gun": "",
        "vendor_description": "",
        "crawl_status": "failed",
        "enrichment_confidence": "",
        "confidence_notes": "Re-listed from san-joaquin county entry. Website enrichment previously failed.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Bay Area Tactical Group (BAT Tactical)",
        "instructor_names": "",
        "email": "",
        "phone": "(415) 568-6803",
        "website_url": "https://www.battactical.com",
        "booking_capability": "direct_booking",
        "city": "San Carlos",
        "state": "CA",
        "address": "827 Cherry Ln, San Carlos, CA 94070",
        "price_16hr_full": "400",
        "price_8hr_renewal": "200",
        "price_add_a_gun": "",
        "vendor_description": "Bay Area Tactical Group (BAT Tactical) is a premier firearms training destination in the Bay Area led by certified and experienced instructors. They offer comprehensive tactical and firearms training for all skill levels, from basic handgun and rifle courses to advanced defensive strategies. The company operates multiple ranges including a private ranch location and emphasizes safety as their top priority while creating a supportive learning environment.",
        "crawl_status": "success",
        "enrichment_confidence": "medium",
        "confidence_notes": "Re-listed from marin county entry. Clear pricing for CCW courses. Direct booking via shopping cart.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Dobbs Firearm Training",
        "instructor_names": "Charles Dobbs",
        "email": "training@dobbsfirearmtraining.com",
        "phone": "(707) 430-0090",
        "website_url": "https://dobbsfirearmtraining.com",
        "booking_capability": "direct_booking",
        "city": "Richmond",
        "state": "CA",
        "address": "3155 Goodrick Ave, Richmond, CA 94801",
        "price_16hr_full": "",
        "price_8hr_renewal": "265",
        "price_add_a_gun": "",
        "vendor_description": "Dobbs Firearm Training provides California CCW training courses, specializing in 8-hour SB2 training requirements for permit renewals. They serve multiple counties including Calaveras, Contra Costa, Solano, Napa, Sacramento, and Yolo County. Currently operating from Richmond Rod & Gun Club.",
        "crawl_status": "success",
        "enrichment_confidence": "medium",
        "confidence_notes": "Re-listed from solano county entry. Clear renewal pricing ($265) and direct booking. No 16-hour initial course pricing found. Training at Richmond Rod & Gun Club.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Progressive Accuracy Training Group, LLC",
        "instructor_names": "Stephen Perrilliat",
        "email": "",
        "phone": "(925) 787-6224",
        "website_url": "https://www.progressiveaccuracy.com",
        "booking_capability": "",
        "city": "Antioch",
        "state": "CA",
        "address": "",
        "price_16hr_full": "",
        "price_8hr_renewal": "",
        "price_add_a_gun": "",
        "vendor_description": "",
        "crawl_status": "success",
        "enrichment_confidence": "low",
        "confidence_notes": "Re-listed from marin county entry. Website content previously appeared corrupted/encoded - unable to extract data.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    # --- 4 new vendors with full enrichment ---
    {
        "county": "contra-costa",
        "vendor_name": "Delta Tactical Training Group",
        "instructor_names": "",
        "email": "info@deltatacticaltraining.com",
        "phone": "(925) 775-4777",
        "website_url": "https://deltatacticalgroup.com",
        "booking_capability": "direct_booking",
        "city": "Antioch",
        "state": "CA",
        "address": "2504 Verne Roberts Cir, Suite 103, Antioch, CA 94509",
        "price_16hr_full": "450",
        "price_8hr_renewal": "225",
        "price_add_a_gun": "",
        "vendor_description": "Delta Tactical Training Group is a veteran-owned, civilian firearms and self-defense training company established in 2011 in the San Francisco Bay Area. They offer CCW courses, basic and intermediate handgun training, and active shooter response courses with law enforcement, military, and NRA instructors. They serve Contra Costa County Sheriff's Office, Antioch PD, Concord PD, Martinez PD, Brentwood PD, Pleasant Hill PD, Pittsburg PD, and Sacramento County.",
        "crawl_status": "success",
        "enrichment_confidence": "high",
        "confidence_notes": "Clear pricing for 16hr CCW ($450) and 8hr renewal ($225). Direct booking via online shopping cart. Full address verified via website and Yelp. Veteran-owned business established 2011.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Gun Kraft",
        "instructor_names": "Robin Yang",
        "email": "robin@gunkraft.com",
        "phone": "(408) 515-3536",
        "website_url": "https://www.gunkraft.com",
        "booking_capability": "inquiry_only",
        "city": "San Leandro",
        "state": "CA",
        "address": "3001 Davis St, San Leandro, CA",
        "price_16hr_full": "400",
        "price_8hr_renewal": "225",
        "price_add_a_gun": "",
        "vendor_description": "Gun Kraft provides comprehensive CCW training at the San Leandro Rifle & Pistol Range, focusing on practical self-defense skills beyond shooting. Their curriculum covers situational awareness, California gun laws, use of force decision-making, emergency trauma care, low-light techniques, and holster selection. Led by instructors with over forty years of combined military and law enforcement experience, their training meets CCW requirements for Contra Costa County, Alameda County, and numerous Bay Area police departments.",
        "crawl_status": "success",
        "enrichment_confidence": "high",
        "confidence_notes": "Clear pricing for 16hr CCW ($400) and 8hr renewal ($225). Training explicitly approved for Contra Costa County. Detailed curriculum available. Training at San Leandro Rifle & Pistol Range.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "LEO Defensive Concepts, LLC",
        "instructor_names": "Joe Leonardo; Archie Chu",
        "email": "mrjoeleo@yahoo.com",
        "phone": "(209) 321-9692",
        "website_url": "https://www.leodefensiveconcepts.com",
        "booking_capability": "unclear",
        "city": "Tracy",
        "state": "CA",
        "address": "4000 Dagnino Rd, Livermore, CA 94551",
        "price_16hr_full": "425",
        "price_8hr_renewal": "225",
        "price_add_a_gun": "",
        "vendor_description": "LEO Defensive Concepts, LLC is a defensive firearms training company founded by law enforcement and medical professionals. Led by retired officers Joe Leonardo (29 years LE, 20 years SWAT) and Archie Chu (20 years LE), they offer tactically driven courses including CCW certification, pistol/rifle/shotgun training, and tactical medical courses. Training is conducted at the Livermore Pleasanton Rod and Gun Club and meets requirements for Contra Costa County, Alameda County, San Francisco County, San Mateo County, and other jurisdictions.",
        "crawl_status": "success",
        "enrichment_confidence": "medium",
        "confidence_notes": "Clear pricing for 16hr CCW ($375 + $50 range fee = $425) and 8hr renewal ($200 + $25 range fee = $225). Course explicitly lists Contra Costa County. Detailed instructor backgrounds. Registration process unclear - no obvious online booking.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
    {
        "county": "contra-costa",
        "vendor_name": "Dapper Defense",
        "instructor_names": "",
        "email": "",
        "phone": "(510) 385-3147",
        "website_url": "https://dapperdefense.net",
        "booking_capability": "inquiry_only",
        "city": "",
        "state": "CA",
        "address": "",
        "price_16hr_full": "400",
        "price_8hr_renewal": "275",
        "price_add_a_gun": "50",
        "vendor_description": "Dapper Defense provides CCW training and NRA-certified firearms instruction in the East Bay area. The instructor holds multiple certifications including NRA Certified Instructor (Pistol, Shotgun, CCW, Personal Protection), NRA Law Enforcement Certified Instructor, USCCA Certified Instructor, BSIS Certified Instructor, DOJ CCW Certified Instructor (#067), and COTCCC Tactical Combat Casualty Care certification. Classes are by appointment only.",
        "crawl_status": "success",
        "enrichment_confidence": "low",
        "confidence_notes": "Pricing listed on website is for Santa Clara County and may differ for Contra Costa ($400 + $25 range fee for 16hr, $275 + $25 range fee for renewal, $50 add-a-gun). No specific city or address found beyond 'East Bay'. Instructor name not publicly listed. By appointment only.",
        "logo_path": "",
        "instructor_image_paths": "",
        "training_image_paths": "",
        "enriched_at": TIMESTAMP,
    },
]

with open(CSV_PATH, "a", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=HEADERS)
    for v in vendors:
        writer.writerow(v)

print(f"Appended {len(vendors)} contra-costa vendor rows to {CSV_PATH}")
