-- All 58 California counties. Safe to re-run: skips rows that already match slug.
insert into counties (name, state, slug) values
  ('Alameda', 'CA', 'alameda'),
  ('Alpine', 'CA', 'alpine'),
  ('Amador', 'CA', 'amador'),
  ('Butte', 'CA', 'butte'),
  ('Calaveras', 'CA', 'calaveras'),
  ('Colusa', 'CA', 'colusa'),
  ('Contra Costa', 'CA', 'contra-costa'),
  ('Del Norte', 'CA', 'del-norte'),
  ('El Dorado', 'CA', 'el-dorado'),
  ('Fresno', 'CA', 'fresno'),
  ('Glenn', 'CA', 'glenn'),
  ('Humboldt', 'CA', 'humboldt'),
  ('Imperial', 'CA', 'imperial'),
  ('Inyo', 'CA', 'inyo'),
  ('Kern', 'CA', 'kern'),
  ('Kings', 'CA', 'kings'),
  ('Lake', 'CA', 'lake'),
  ('Lassen', 'CA', 'lassen'),
  ('Los Angeles', 'CA', 'los-angeles'),
  ('Madera', 'CA', 'madera'),
  ('Marin', 'CA', 'marin'),
  ('Mariposa', 'CA', 'mariposa'),
  ('Mendocino', 'CA', 'mendocino'),
  ('Merced', 'CA', 'merced'),
  ('Modoc', 'CA', 'modoc'),
  ('Mono', 'CA', 'mono'),
  ('Monterey', 'CA', 'monterey'),
  ('Napa', 'CA', 'napa'),
  ('Nevada', 'CA', 'nevada'),
  ('Orange', 'CA', 'orange'),
  ('Placer', 'CA', 'placer'),
  ('Plumas', 'CA', 'plumas'),
  ('Riverside', 'CA', 'riverside'),
  ('Sacramento', 'CA', 'sacramento'),
  ('San Benito', 'CA', 'san-benito'),
  ('San Bernardino', 'CA', 'san-bernardino'),
  ('San Diego', 'CA', 'san-diego'),
  ('San Francisco', 'CA', 'san-francisco'),
  ('San Joaquin', 'CA', 'san-joaquin'),
  ('San Luis Obispo', 'CA', 'san-luis-obispo'),
  ('San Mateo', 'CA', 'san-mateo'),
  ('Santa Barbara', 'CA', 'santa-barbara'),
  ('Santa Clara', 'CA', 'santa-clara'),
  ('Santa Cruz', 'CA', 'santa-cruz'),
  ('Shasta', 'CA', 'shasta'),
  ('Sierra', 'CA', 'sierra'),
  ('Siskiyou', 'CA', 'siskiyou'),
  ('Solano', 'CA', 'solano'),
  ('Sonoma', 'CA', 'sonoma'),
  ('Stanislaus', 'CA', 'stanislaus'),
  ('Sutter', 'CA', 'sutter'),
  ('Tehama', 'CA', 'tehama'),
  ('Trinity', 'CA', 'trinity'),
  ('Tulare', 'CA', 'tulare'),
  ('Tuolumne', 'CA', 'tuolumne'),
  ('Ventura', 'CA', 'ventura'),
  ('Yolo', 'CA', 'yolo'),
  ('Yuba', 'CA', 'yuba')
on conflict (slug) do nothing;
